version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    allow:
      - dependency-name: "beautifulsoup4"
      - dependency-name: "rapidfuzz"
      - dependency-name: "requests"
      - dependency-name: "streamlit"
      - dependency-name: "mkdocs-material"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
